---
name: Python Tests

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install tox
      - name: Validate formatting
        run: tox -e format

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        tox_env:
          - py37-dj22-wt211
          - py37-dj22-wt212
          - py37-dj22-wt213
          - py38-dj22-wt211
          - py38-dj22-wt212
          - py38-dj22-wt213
          - py37-dj30-wt211
          - py37-dj30-wt212
          - py37-dj30-wt213
          - py38-dj30-wt211
          - py38-dj30-wt212
          - py38-dj30-wt213
        include:
          - python-version: 3.7
            tox_env: py37-dj22-wt211
          - python-version: 3.7
            tox_env: py37-dj22-wt212
          - python-version: 3.7
            tox_env: py37-dj22-wt213
          - python-version: 3.8
            tox_env: py38-dj22-wt211
          - python-version: 3.8
            tox_env: py38-dj22-wt212
          - python-version: 3.8
            tox_env: py38-dj22-wt213
          - python-version: 3.7
            tox_env: py37-dj30-wt211
          - python-version: 3.7
            tox_env: py37-dj30-wt212
          - python-version: 3.7
            tox_env: py37-dj30-wt213
          - python-version: 3.8
            tox_env: py38-dj30-wt211
          - python-version: 3.8
            tox_env: py38-dj30-wt212
          - python-version: 3.8
            tox_env: py38-dj30-wt213
          - python-version: 3.9
            tox_env: py39-dj31-wt214
          - python-version: 3.9
            tox_env: py39-dj32-wt214
          - python-version: 3.9
            tox_env: py39-dj31-wt215
          - python-version: 3.9
            tox_env: py39-dj32-wt215
          - python-version: 3.9
            tox_env: py39-dj32-wt216
          - python-version: 3.9
            tox_env: py39-dj40-wt216
          - python-version: 3.9
            tox_env: py39-dj32-wt30
          - python-version: 3.9
            tox_env: py39-dj40-wt30
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -e ${{ matrix.tox_env }} --index-url=https://pypi.python.org/simple/
      - name: Prepare artifacts
        run: mkdir -p .coverage-data && mv .coverage.* .coverage-data/
      - uses: actions/upload-artifact@master
        with:
          name: coverage-data
          path: .coverage-data/
